name: Tests & Linting
run-name: Tests & Linting by @${{ github.actor }}

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files
